- name: Purge older versions of docker
  become:  true
  apt:  name={{item}} state=absent purge=yes
  with_items:
  - docker
  - docker-engine
  - docker.io
  ignore_errors: yes

- name: Install some pre-requisites
  become:  true
  apt:  name={{item}} state=present
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

- name: Add docker repo key
  become:  true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  become:  true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present

- name: Install docker
  become:  true
  apt:  name={{item}} state=present
  with_items:
  - docker-ce

- name: Enable docker at boot
  become:  true
  systemd:
    name: docker
    enabled: True

- name: Create docker.service.d
  become:  true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Write docker http-proxy.conf
  become:  true
  template:
    src=http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf backup=yes

- name: restart docker service, in all cases, also issue daemon-reload to pick up config changes
  become:  true
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
